'use client'

import { memo, Profiler, useLayoutEffect, useMemo, useRef, useState, useSyncExternalStore, type KeyboardEvent, type PointerEvent } from 'react'
import { Button } from '@/components/kit/button'
import { closeOnBackdrop, openOnCancel, sheet, title } from '@/components/kit/dialog'
import { ring, slimScrollbar } from '@/components/kit/greyed'
import { Copy, Eye, EyeOff, Moon, Pencil, Star } from '@/components/kit/icons'
import { TextInput } from '@/components/kit/input'
import { AutoGeneratedRow, FeedlessNote } from '@/components/editor/auto-generated'
import { MainFeedChip } from '@/components/kit/badge'
import { glyphOf, LayerThumb, LayersRow, SiteWideGroup } from '@/components/kit/layers-row'
import { Menu } from '@/components/kit/select'
import { arrowKeys, openMenu } from '@/lib/menu'
import { captureLayout, landingAt, shift, slotTop, type Layout, type Store } from '@/lib/reorder'
import { landWithin } from '@/lib/editor'
import { canvasFirst, counted, useHanded, useStable } from '@/lib/renders'
import { MAKE_MAIN_FEED } from '@/lib/data-group'
import { GHOST_WORDS, type SurfaceId } from '@/lib/ghost-surfaces'
import { PAYWALL_WORDS } from '@/lib/paywall'

/* B7 · LAYERS (`B Missing Surfaces.dc.html`:1538-1580), AS R-126 AMENDS IT — the panel body, and Story 5.4's whole
   Layers surface. The `<aside>`, its title and its fold stay in `editor.tsx`; everything below them is here, so that
   file keeps the shape Story 5.1 gave it.

   R-126 (owner, 2026-09-18, on the deployed story) IS THE LATER WORD OVER B7, and is recorded as a ruling because
   R-74 makes the export the design authority. Five things, all of them width: the two groups are drawn THE SAME —
   heading, right-aligned mono count, rows — with a hairline between them instead of a pinned white card and its
   globe; `Site-wide` and its template count fit ONE line; the row's name shrank to `text-helper-caption`; the eye
   left the row for the `⋯` menu, which is now the row's only control; and B7's footed note is gone, because the
   Site-wide heading already carries the count it repeated.

   TWO GROUPS, AND THE BOUNDARY IS STILL THE RULE. A section is never reordered from one group into the other
   (FR-D5's shared instance), and a drag that leaves its own group lands at that group's own end (`landingAt` never counts past the
   list it measured, as P0-3's list does not). The hairline says so
   where B7's card outline used to.

   NEITHER COUNT IS WRITTEN DOWN (standing rule 4): the site group's is how many canvases `lib/editor.ts` opens,
   which grows on its own as Story 5.5 opens more, and the page group's is its own rows.

   NOTHING REORDERS UNTIL THE DROP (EXPERIENCE.md :308, the owner's finding 9 of 2026-09-13). A dashed slot the
   dragged row's height shows where it lands and the rows between are TRANSLATED — nothing moves in the DOM, so the
   grip keeps its pointer capture — and one `moveSection` runs on release. The arithmetic is `lib/reorder.ts`, the
   same numbers P0-3's item list drags by. The drag lives in a STORE OF ONE VALUE that `editor.tsx` holds (`lib/reorder.ts`'s
   `oneValue`), because the canvas pill's grip drives the same reorder from the other side of the frame: whichever grip is
   held, this panel draws the slot — and since Story 5.23b it is the only thing that subscribes, so a pointer move redraws
   the slot and the rows it slides and never the editor. A drop that moved is handed to React a task later (R-210): the
   slot and the slid rows stay as they are until the moved rows arrive here, and then the drag is let go, so Layers never
   shows the old order in between.

   EACH ROW REDRAWS ONLY WHAT TOUCHED IT (Story 5.23b, R-208). A row is a module-level `memo` component given its own
   fields, its selected and hovered flags, its tab stop and its slide — all primitives — and ONE object of actions for the
   panel's life (`lib/renders.ts`'s `useStable`), so a hover redraws the two rows whose wash changed and not the other
   forty, each with its closed menu. React's `<Profiler>` inside it counts its renders for the keyboard gate.

   EVERY DRAG HAS A KEYBOARD PATH (UX-DR10), and R-126 costs it nothing. The ROW is the one tab stop per section —
   roving tabindex, D8e's ring on the row — and carries the keys: `↑ ↓` move focus (through both groups, in the order
   they are drawn), `⌥↑`/`⌥↓` move the section inside its own group with the move announced politely in
   `moveSection`'s words (UX-DR12), `Enter` selects, `Space` toggles visibility — a KEY, not a control, so it survived
   the eye's removal. The grip is `aria-hidden` and pointer-only; the `⋯` keeps its own tab stop.

   R-123's THIRD GROUND is the empty space BELOW THE ROWS, and its geometry is read from the last ROW — not from the
   list's last element child, which is the rename dialog. A group heading and a group's padding are not ground: a
   miss there while reaching for a row would cost the selection.

   THE SITE-WIDE ROW'S TWO REFUSALS. Duplicate is ABSENT from its menu (UX-DR3) — a header is one shared instance, not
   a copy per page. Delete and Hide ask first, in a confirm that lives in `editor.tsx` rather than here, because the
   canvas pill's Delete must open the SAME one.

   R-133 (owner, 2026-09-18) EXTENDS R-126 RATHER THAN REVERSING IT: the `⋯` gains a fifth item, "Clear dark
   overrides", by the owner's own word. The `⋯` is still the row's only control and Hide/Show still leads its menu.
   The item is ABSENT where the section carries no usable override — UX-DR3, and exactly the shape Duplicate already
   uses on a site-wide row below — because a menu item explains nothing about itself, while the Controls panel's row
   beside "Reset this design" is always present and says there is nothing to clear. Both open the SAME confirm, which
   is `editor.tsx`'s for Delete's and Hide's reason.

   STORY 5.19 ADDS TWO OF D5c's PIECES AND KEEPS R-126: the main feed's row carries D5c's MAIN FEED chip before its
   `⋯`, and a visible secondary feed of a paginated page offers "Make this the main feed" SECOND in its menu, after
   Hide/Show — absent everywhere else (UX-DR3). The Layers menu keeps its built words, Duplicate and Delete, not D5c's
   "Duplicate section / Remove section" (R-170, a routine call stated in the spec). And a Tag or Author page with no
   visible feed says so at the panel's head, in D5a's marker's shape.

   R-217 (owner, 2026-09-28, as amended the same day — DW-188, Story 5.24e): A ROW'S POINTER OUTLINES ITS SECTION and only
   a click scrolls to it. Story 5.2's mirroring ran one way, the canvas's hover into this panel's wash; now a mouse over a
   row points at its section too (`onPoint`), which draws S4b's outline and name tag over it and nothing pressable — no
   pill, no insertion hairline — and never moves the page: R-156's reveal stays the click's. A touch never points, and
   keyboard focus keeps D8e's ring and nothing more. */

/** One row, as the editor hands it over. */
export type LayerRow = {
  /** the `project_templates` key — `site` for a shared instance, the canvas key for a page section */
  doc: string
  instanceId: string
  layerName: string
  hidden: boolean
  /** this row's position in its OWN doc's instances — what `moveSection` is given */
  at: number
  /** Story 5.6, R-133 — does this section carry a dark override an emitter could use? The engine's own answer
   *  (`darkOverridesInForce`), derived by the caller. False means the menu item is ABSENT, not greyed. */
  darkOverride: boolean
  /** Story 5.19 — this is its page's MAIN FEED: D5c's chip sits on the row, before the `⋯` */
  mainFeed: boolean
  /** Story 5.19 — **Make this the main feed** is offered: a visible feed of a paginated page that is not already it.
   *  False means ABSENT (UX-DR3), on the main feed, a hidden row, a section that is no feed and any other page. */
  canLead: boolean
  /** DW-281 (Story 5.24e) — the design's category, which picks the row's picture (`glyphOf`) */
  category: string
  /** DW-187 (Story 5.24e) — a site-wide FOOTER, drawn last on the page: a move keeps it in its band (`landWithin`) */
  footer: boolean
}

/** The drag in flight, over one doc's own rows. Held by `editor.tsx`, because the canvas pill starts one too —
 *  `via` says which grip, because only a row's own drag lifts the row: a pill drag moves the section on the CANVAS,
 *  and this panel shows only where it will land. `landing`: dropped, its move handed to React a task later (R-210) —
 *  the slot stays until the moved rows arrive, and nothing else may start or move it meanwhile. */
export type SectionDrag = { doc: string; from: number; to: number; dy: number; via: 'layers' | 'pill'; landing?: true }

/** STORY 5.21's FIX (the owner's finding, 2026-09-26, Question 2 ruled option 1): Ghost's two surfaces on the canvas —
 *  its announcement bar and Portal's button — named as rows under "From your Ghost site", each with a section row's own
 *  Hide / Show and nothing else: no drag, no rename, no Duplicate, no Delete, because they are the site's, not the doc's.
 *  Hidden is the builder's, kept in this browser (`lib/ghost-surfaces.ts`). Absent where the site shows no Ghost surface,
 *  and each row only while the site shows its surface (R-215, Story 5.24e — `rowsOn`). */
export type GhostRows = {
  rows: readonly { id: SurfaceId; name: string; hidden: boolean }[]
  selectedId: SurfaceId | null
  hoveredId: SurfaceId | null
  onSelect: (id: SurfaceId) => void
  onToggleHidden: (id: SurfaceId) => void
  /** R-217 — a mouse over the row points at its shim, as over a section's row; null as it leaves */
  onPoint?: (id: SurfaceId | null) => void
}

export type LayersProps = {
  /** the site doc's instances in doc order — the Site-wide group's rows */
  site: readonly LayerRow[]
  /** this canvas's own instances in doc order */
  page: readonly LayerRow[]
  /** the canvas's D5b label, for `THIS PAGE · {LABEL}` */
  label: string
  /** the site doc's key, so a row knows which group it is in */
  siteKey: string
  /** how many canvases the editor opens — derived by the caller, never written down */
  templates: number
  /** Story 5.5 — this canvas is untouched, so D5a's marker leads the panel — the marker's ONE place since R-130 */
  autoGenerated: boolean
  /** Story 5.16 — the marker's own sentence, where it is not D5a's: page 2's "Copy of page 1…" while it follows */
  markerWords?: string
  /** `{doc}:{instanceId}` — a composite, because `instanceId` is unique per doc and not across them */
  selectedKey: string | null
  hoveredKey: string | null
  /** the drag in flight, in the editor's store of one value — this panel is its only subscriber (Story 5.23b) */
  drag: Store<SectionDrag | null>
  /** Story 5.17 — a session reading along: rows select, nothing reorders and the ⋯ menu stays shut (R-192) */
  readOnly?: boolean
  /** the press that selects; a press on a ROW never deselects (R-123) */
  onSelect: (row: LayerRow) => void
  /** R-217 (DW-188) — a mouse over a row points at its section (outline and name tag, never a scroll); null as it leaves */
  onPoint?: (row: LayerRow | null) => void
  /** R-123's third ground: the empty space below the rows */
  onGround: () => void
  onToggleHidden: (row: LayerRow) => void
  /** the refusal sentence, or null when the rename landed */
  onRename: (row: LayerRow, name: string) => string | null
  onDuplicate: (row: LayerRow) => void
  onRemove: (row: LayerRow) => void
  /** Story 5.6, R-133 — opens the editor's ONE "Clear dark overrides" confirm for this row */
  onClearDark: (row: LayerRow) => void
  /** Story 5.19 — D5c's **Make this the main feed**: one edit, announced by the editor */
  onMakeMainFeed: (row: LayerRow) => void
  /** Story 5.19 — FR-H2's archive case: the sentence for a Tag or Author page with no visible feed, or null */
  feedless?: string | null
  /** the drop, or an `⌥`-arrow: `to` is the position in that row's own doc. Answers the words to announce. */
  onMove: (row: LayerRow, to: number) => string | null
  /** Story 5.21's Fix — the rows for Ghost's two surfaces, where the canvas draws them */
  ghost?: GhostRows
}

/** A row's identity across both groups: `instanceId` is unique inside a doc, not between two. */
const keyOf = (row: LayerRow) => `${row.doc}:${row.instanceId}`

const NAME_FIELD = 'layers-rename-name'

const HEADING = 'text-helper-caption font-semibold tracking-[0.04em] text-ink-soft uppercase'
const COUNT = 'font-mono text-helper-caption text-ink-soft'

/** What a row does — ONE object for the panel's life (Story 5.23b), each action calling the panel's latest render. */
type RowActions = {
  key: (row: LayerRow, event: KeyboardEvent<HTMLDivElement>) => void
  select: (row: LayerRow) => void
  toggle: (row: LayerRow) => void
  lead: (row: LayerRow) => void
  rename: (row: LayerRow) => void
  duplicate: (row: LayerRow) => void
  clearDark: (row: LayerRow) => void
  remove: (row: LayerRow) => void
  grab: (row: LayerRow, event: PointerEvent<HTMLSpanElement>) => void
  drag: (row: LayerRow, event: PointerEvent<HTMLSpanElement>) => void
  drop: (row: LayerRow) => void
  cancel: () => void
  point: (row: LayerRow | null) => void
}

type RowProps = LayerRow & {
  selected: boolean
  hovered: boolean
  /** the panel's one tab stop (roving tabindex) */
  tabStop: boolean
  /** the drag's part in this row — lifted by its own grip, sliding aside, or neither — and how far, in pixels */
  motion: 'lifted' | 'sliding' | null
  translate: number
  readOnly: boolean
  siteKey: string
  actions: RowActions
}

/* ONE ROW — a MODULE-LEVEL `memo` component (Story 5.23b). Declared inside `Layers` it would be a NEW type on every render
   and remount each row, and a remounted grip loses the pointer capture the drag holds; declared here it keeps its
   instance, and skips its render whenever its props — every one a primitive but the one actions object — are unchanged. */
const Row = memo(function Row({ selected, hovered, tabStop, motion, translate, readOnly, siteKey, actions, ...row }: RowProps) {
  // the doc is part of the id: an `instanceId` is unique inside a doc, not across the two groups
  const menu = `layers-menu-${row.doc}-${row.instanceId}`
  return (
    <Profiler id="layers-row" onRender={counted}>
      <LayersRow
        name={row.layerName}
        shown={!row.hidden}
        selected={selected}
        hovered={hovered}
        data-layer-row={keyOf(row)}
        tabIndex={tabStop ? 0 : -1}
        aria-describedby="layers-how"
        onKeyDown={(event) => actions.key(row, event)}
        onSelect={() => actions.select(row)}
        // R-217 (DW-188): a MOUSE over the row points at its section — a touch never points, and focus keeps D8e's ring
        onPointerEnter={(event) => event.pointerType !== 'touch' && actions.point(row)}
        onPointerLeave={(event) => event.pointerType !== 'touch' && actions.point(null)}
        style={motion === null ? undefined : { translate: `0 ${translate}px` }}
        className={`relative ${motion === 'lifted' ? 'z-10 shadow-lg motion-safe:rotate-2' : motion === 'sliding' ? 'motion-safe:transition-[translate] motion-safe:duration-150' : ''}`}
        // Story 5.19 — D5c's Layers chip (:290), after the name and before the `⋯`
        chip={row.mainFeed ? <MainFeedChip /> : undefined}
        // DW-281 (Story 5.24e) — its own kind's picture, S4's five (`glyphOf`)
        thumb={<LayerThumb glyph={glyphOf(row.category)} />}
        // R-192: absent, not dead — the Kit's row draws no grab cursor when it is given no grip
        gripProps={readOnly ? undefined : {
          onPointerDown: (event) => actions.grab(row, event),
          onPointerMove: (event) => actions.drag(row, event),
          onPointerUp: () => actions.drop(row),
          onPointerCancel: actions.cancel,
        }}
        overflow={
          <>
            <button
              type="button"
              disabled={readOnly}
              aria-label={`More for ${row.layerName}`}
              popoverTarget={menu}
              onClick={(event) => {
                const el = document.getElementById(menu)
                if (el) openMenu(el, event.currentTarget, { side: 'down', align: 'right' })
              }}
              className={`inline-flex size-[22px] shrink-0 items-center justify-center rounded-[6px] text-[12px] font-bold tracking-[1px] text-ink-soft hover:bg-paper hover:text-ink ${ring}`}
            >
              …
            </button>
            <div id={menu} popover="auto" onKeyDown={arrowKeys} className="border-0 bg-transparent p-0">
              <Menu
                label={row.layerName}
                items={[
                  // R-126: Hide/Show is a MENU ROW now, not an eye on the row — the row's width belongs to its name.
                  // It leads, because it is the one a layer list is reached for most.
                  {
                    label: row.hidden ? 'Show' : 'Hide',
                    icon: row.hidden ? <Eye size={13} /> : <EyeOff size={13} />,
                    onSelect: () => actions.toggle(row),
                  },
                  // Story 5.19 — D5c's first item, SECOND here because R-126 keeps Hide/Show first; absent wherever it
                  // could do nothing (UX-DR3): the main feed itself, a hidden row, a section that is no feed
                  ...(row.canLead ? [{ label: MAKE_MAIN_FEED, icon: <Star size={13} />, onSelect: () => actions.lead(row) }] : []),
                  { label: 'Rename', icon: <Pencil size={13} />, onSelect: () => actions.rename(row) },
                  // FR-D5: a site-wide section is ONE shared instance, so there is nothing to copy — absent, not
                  // greyed and not a refusal (UX-DR3)
                  ...(row.doc === siteKey ? [] : [{ label: 'Duplicate', icon: <Copy size={13} />, onSelect: () => actions.duplicate(row) }]),
                  // R-133's SECOND entry point, absent for the same reason Duplicate is above: a menu item cannot
                  // explain itself, so a section with nothing to clear simply does not offer it
                  ...(row.darkOverride ? [{ label: 'Clear dark overrides', icon: <Moon size={13} />, onSelect: () => actions.clearDark(row) }] : []),
                  { label: 'Delete', danger: true, onSelect: () => actions.remove(row) },
                ]}
              />
            </div>
          </>
        }
      />
    </Profiler>
  )
})

export const Layers = memo(function Layers({
  site,
  page,
  label,
  siteKey,
  templates,
  autoGenerated,
  markerWords,
  selectedKey,
  hoveredKey,
  drag,
  readOnly = false,
  onSelect,
  onPoint,
  onGround,
  onToggleHidden,
  onRename,
  onDuplicate,
  onRemove,
  onClearDark,
  onMakeMainFeed,
  onMove,
  feedless = null,
  ghost,
}: LayersProps) {
  const all = [...site, ...page]
  const panel = useRef<HTMLDivElement>(null)
  const siteList = useRef<HTMLDivElement>(null)
  const pageList = useRef<HTMLDivElement>(null)
  /** the rows of the dragged group as they stood when the press landed — captured for a pill-started drag too */
  const layout = useRef<Layout>({ tops: [], heights: [], gap: 0 })
  const startY = useRef(0)
  /** roving tabindex: the row the panel offers Tab, by instanceId — the first row until one is stepped onto. Handed
   *  (Story 5.23b): a move's focus is handed over with the rows it follows (R-210) */
  const [current, setCurrent] = useHanded<string | null>(null)
  /** the row to put focus back on after a render that reordered the rows, so a move follows its section */
  const [focusOn, setFocusOn] = useHanded<string | null>(null)
  const [renaming, setRenaming] = useState<LayerRow | null>(null)
  const [nameError, setNameError] = useState<string | null>(null)
  const rename = useRef<HTMLDialogElement>(null)

  // the tab stop follows the selection until a key steps it elsewhere, so Tab into Layers lands on the selected row
  const tabAt = current !== null && all.some((r) => keyOf(r) === current) ? current : (selectedKey ?? (all[0] ? keyOf(all[0]) : null))
  const rowEl = (key: string) => panel.current?.querySelector<HTMLElement>(`[data-layer-row="${CSS.escape(key)}"]`)

  // a LAYOUT effect (Story 5.23b): a move reaches these rows a task after the canvas (R-210's hand-over), and its reorder
  // takes the focus off the row it moves — so it is put back in that same commit, before a second key can reach the page
  useLayoutEffect(() => {
    if (focusOn === null) return
    rowEl(focusOn)?.focus()
    setFocusOn(null)
    // `rowEl` reads a ref; the row to focus is the whole dependency
  }, [focusOn])

  // the drag in flight — read here and nowhere else in the editor's tree, so a pointer move redraws this panel's slot
  // and the rows it slides (Story 5.23b)
  const inFlight = useSyncExternalStore(drag.subscribe, drag.get, () => null)
  // the layout is read ONCE per drag, from whichever group started it: a slot measured against rows that are already
  // sliding would chase itself, and a drag started by the canvas pill has no layout of its own to hand over
  const dragDoc = inFlight?.doc ?? null
  const [, measured] = useState(0)
  useLayoutEffect(() => {
    if (dragDoc === null) return
    const list = dragDoc === siteKey ? siteList.current : pageList.current
    layout.current = captureLayout([...(list?.querySelectorAll<HTMLElement>('[data-layer-row]') ?? [])])
    // the render that started the drag drew the slot from the PREVIOUS layout; one re-render before paint corrects it
    measured((n) => n + 1)
    // `drag.to` changes on every pointer move and must not re-measure
  }, [dragDoc, siteKey])

  // R-210: A DROP THAT MOVED IS LET GO WHEN ITS MOVE LANDS — the rows are handed over a frame after the canvas, and until
  // they are the slot and the slid rows stay as they were, so Layers never shows the old order in between. The rows
  // arriving is these two props changing; before paint, so the new order and the slot's going are one frame.
  useLayoutEffect(() => {
    if (drag.get()?.landing) drag.set(null)
  }, [site, page, drag])

  /** Rename's one action, reached by Save and by Enter in the field. The field is the DOM's, read by its own id. */
  const save = () => {
    if (!renaming) return
    const refused = onRename(renaming, (document.getElementById(NAME_FIELD) as HTMLInputElement | null)?.value ?? '')
    if (refused !== null) {
      setNameError(refused)
      return
    }
    rename.current?.close()
  }

  /** True when the move landed. The announce is the editor's to read out, so the pill's drop announces through the same
   *  live region. R-210: the move reaches these rows in the editor's hand-over, so the row's focus goes in the SAME one —
   *  set now, it would land before the move and the reorder that follows would take it away. */
  const move = (row: LayerRow, to: number) => {
    let moved = false
    canvasFirst(() => {
      if (onMove(row, to) === null) return
      moved = true
      setCurrent(keyOf(row))
      setFocusOn(keyOf(row))
    })
    return moved
  }

  const onRowKey = (row: LayerRow, event: KeyboardEvent<HTMLDivElement>) => {
    // a key pressed in the ⋯ or its menu belongs to that control, not to the row
    if (event.target !== event.currentTarget) return
    const own = row.doc === siteKey ? site : page
    if (event.altKey && (event.key === 'ArrowUp' || event.key === 'ArrowDown')) {
      event.preventDefault()
      const to = row.at + (event.key === 'ArrowUp' ? -1 : 1)
      // at either end the key does nothing — and DW-187 (Story 5.24e): at either end of the row's BAND, a footer never
      // rising above a header nor a header sinking below a footer, so Layers' order stays the page's
      if (to < 0 || to >= own.length || landWithin(own.map((r) => r.footer), row.at, to) !== to) return
      move(row, to)
    } else if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
      const to = all[all.findIndex((r) => keyOf(r) === keyOf(row)) + (event.key === 'ArrowUp' ? -1 : 1)]
      if (!to) return
      event.preventDefault()
      setCurrent(keyOf(to))
      setFocusOn(keyOf(to))
    } else if (event.key === 'Enter') {
      event.preventDefault()
      onSelect(row)
    } else if (event.key === ' ') {
      event.preventDefault()
      onToggleHidden(row)
    }
  }

  /* THE ROWS' ACTIONS, one object for the panel's life: each calls this panel's latest committed render, so a row that
     did not change keeps every prop it had and skips its render (Story 5.23b). */
  const rowKey = useStable(onRowKey)
  const select = useStable((row: LayerRow) => onSelect(row))
  const toggle = useStable((row: LayerRow) => onToggleHidden(row))
  const lead = useStable((row: LayerRow) => onMakeMainFeed(row))
  const duplicate = useStable((row: LayerRow) => onDuplicate(row))
  const clearDark = useStable((row: LayerRow) => onClearDark(row))
  const remove = useStable((row: LayerRow) => onRemove(row))
  const startRename = useStable((row: LayerRow) => {
    setNameError(null)
    setRenaming(row)
    // the dialog's field is rendered on the next frame, and it opens on Cancel
    requestAnimationFrame(() => openOnCancel(rename.current))
  })
  const grab = useStable((row: LayerRow, event: PointerEvent<HTMLSpanElement>) => {
    if (event.button !== 0 || drag.get() !== null) return // a second pointer never takes over a live drag, or a landing one
    event.currentTarget.setPointerCapture(event.pointerId)
    startY.current = event.clientY
    drag.set({ doc: row.doc, from: row.at, to: row.at, dy: 0, via: 'layers' })
  })
  const dragTo = useStable((row: LayerRow, event: PointerEvent<HTMLSpanElement>) => {
    const now = drag.get()
    if (now?.doc !== row.doc || now.from !== row.at || now.landing) return
    // DW-187 (Story 5.24e): the dashed slot never leaves the row's band
    const own = row.doc === siteKey ? site : page
    const to = landWithin(own.map((r) => r.footer), row.at, landingAt(layout.current, row.at, event.clientY, startY.current))
    drag.set({ doc: row.doc, from: row.at, to, dy: event.clientY - startY.current, via: 'layers' })
  })
  const drop = useStable((row: LayerRow) => {
    const now = drag.get()
    if (now?.doc !== row.doc || now.from !== row.at || now.landing) return
    // R-210: a drop that moved keeps its slot until the moved rows land (the effect above lets it go); one that moved
    // nothing — or whose move did not land — lets it go now
    if (now.to !== now.from && move(row, now.to)) drag.set({ ...now, landing: true })
    else drag.set(null)
  })
  const cancel = useStable(() => drag.set(null))
  const point = useStable((row: LayerRow | null) => onPoint?.(row))
  const actions = useMemo<RowActions>(
    () => ({ key: rowKey, select, toggle, lead, rename: startRename, duplicate, clearDark, remove, grab, drag: dragTo, drop, cancel, point }),
    [rowKey, select, toggle, lead, startRename, duplicate, clearDark, remove, grab, dragTo, drop, cancel, point],
  )

  const drawRow = (row: LayerRow) => {
    const lifted = inFlight?.doc === row.doc && inFlight.from === row.at && inFlight.via === 'layers'
    const sliding = inFlight?.doc === row.doc
    return (
      <Row
        key={keyOf(row)}
        {...row}
        selected={selectedKey === keyOf(row)}
        hovered={hoveredKey === keyOf(row)}
        tabStop={tabAt === keyOf(row)}
        motion={lifted ? 'lifted' : sliding ? 'sliding' : null}
        translate={lifted ? inFlight.dy : sliding ? shift(inFlight, row.at, layout.current) : 0}
        readOnly={readOnly}
        siteKey={siteKey}
        actions={actions}
      />
    )
  }

  const drawGroup = (rows: readonly LayerRow[], which: 'site' | 'page') => (
    // `relative`: the dashed slot is positioned against this group's own rows
    <div ref={which === 'site' ? siteList : pageList} className="relative flex flex-col gap-[2px]">
      {inFlight !== null && (inFlight.doc === siteKey) === (which === 'site') ? (
        <div
          aria-hidden
          data-drop-slot
          style={{ top: slotTop(inFlight, layout.current), height: layout.current.heights[inFlight.from] ?? 0 }}
          className="pointer-events-none absolute inset-x-0 rounded-sm border border-dashed border-line-strong bg-paper-sunk"
        />
      ) : null}
      {rows.map(drawRow)}
    </div>
  )

  return (
    <div
      ref={panel}
      // R-123 as amended: the empty space BELOW THE ROWS is a ground, as it is in Figma and Sketch. A row is not, and
      // neither is a group heading, a group's padding or the gap between two rows — a miss there
      // while reaching for a row would cost the selection (review, 2026-09-18). The geometry is the last ROW's, never
      // this container's last element child, which is the note.
      onPointerDown={(event) => {
        if (event.button !== 0 || event.target !== event.currentTarget) return
        const rows = event.currentTarget.querySelectorAll<HTMLElement>('[data-layer-row]')
        const last = rows[rows.length - 1]?.getBoundingClientRect().bottom ?? -Infinity
        if (event.clientY >= last) onGround()
      }}
      // the deployed walk finds the list by this, never by its place in the aside (Story 5.10 added a footer after it)
      data-layers-list
      className={`flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto px-2 py-[10px] ${slimScrollbar}`}
    >
      {/* D5a (:54-57): the marker is about the CANVAS, not a group, so it sits ABOVE both — R-126 drew the two groups
          and their hairline and this takes nothing from either heading. It goes with the first edit (AD-22). */}
      {autoGenerated ? <AutoGeneratedRow words={markerWords} /> : null}
      {/* Story 5.19 — FR-H2's archive case, beside D5a's marker and in its shape, while it is true */}
      {feedless === null ? null : <FeedlessNote words={feedless} />}
      <SiteWideGroup pages={templates}>{drawGroup(site, 'site')}</SiteWideGroup>

      <div className="flex flex-col gap-[2px]">
        <div className="flex items-center gap-[6px] px-[5px] pb-[5px]">
          <span className={`flex-1 ${HEADING}`}>This page · {label}</span>
          <span className={COUNT}>{page.length}</span>
        </div>
        {drawGroup(page, 'page')}
      </div>

      {/* Story 5.21's Fix — "From your Ghost site": the heading in the two groups' shape, the sentence, and one row per
          surface in the Kit's row with the ⋯ → Hide / Show a section row has. Each row is its own tab stop (two, and
          never more: the list is the surfaces'), Enter chooses it and Space hides or shows it. */}
      {ghost === undefined ? null : (
        <div data-ghost-rows className="flex flex-col gap-[2px] border-t border-line pt-[10px]">
          <div className="flex items-center gap-[6px] px-[5px] pb-[5px]">
            <span className={`flex-1 ${HEADING}`}>{GHOST_WORDS.group}</span>
          </div>
          <p className="px-[5px] pb-[5px] text-[11.5px] leading-[1.5] text-ink-soft-aa text-pretty">{GHOST_WORDS.line}</p>
          {ghost.rows.map((row) => {
            const menu = `layers-menu-ghost-${row.id}`
            return (
              <LayersRow
                key={row.id}
                name={row.name}
                shown={!row.hidden}
                selected={ghost.selectedId === row.id}
                hovered={ghost.hoveredId === row.id}
                data-layer-row={`ghost:${row.id}`}
                tabIndex={0}
                aria-describedby="layers-ghost-how"
                onKeyDown={(event) => {
                  if (event.target !== event.currentTarget) return
                  if (event.key === 'Enter') {
                    event.preventDefault()
                    ghost.onSelect(row.id)
                  } else if (event.key === ' ') {
                    event.preventDefault()
                    ghost.onToggleHidden(row.id)
                  }
                }}
                onSelect={() => ghost.onSelect(row.id)}
                // R-217: a mouse over a Ghost row points at its shim, as over a section's row
                onPointerEnter={(event) => event.pointerType !== 'touch' && ghost.onPoint?.(row.id)}
                onPointerLeave={(event) => event.pointerType !== 'touch' && ghost.onPoint?.(null)}
                overflow={
                  <>
                    <button
                      type="button"
                      aria-label={`More for ${row.name}`}
                      popoverTarget={menu}
                      onClick={(event) => {
                        const el = document.getElementById(menu)
                        if (el) openMenu(el, event.currentTarget, { side: 'down', align: 'right' })
                      }}
                      className={`inline-flex size-[22px] shrink-0 items-center justify-center rounded-[6px] text-[12px] font-bold tracking-[1px] text-ink-soft hover:bg-paper hover:text-ink ${ring}`}
                    >
                      …
                    </button>
                    <div id={menu} popover="auto" onKeyDown={arrowKeys} className="border-0 bg-transparent p-0">
                      <Menu
                        label={row.name}
                        items={[{ label: row.hidden ? 'Show' : 'Hide', icon: row.hidden ? <Eye size={13} /> : <EyeOff size={13} />, onSelect: () => ghost.onToggleHidden(row.id) }]}
                      />
                    </div>
                  </>
                }
              />
            )
          })}
          <p id="layers-ghost-how" className="sr-only">{GHOST_WORDS.how}</p>
        </div>
      )}

      <p id="layers-how" className="sr-only">
        Press Enter to select this section, Space to hide or show it, and Option or Alt with the up or down arrow to
        move it.
      </p>
      {/* Rename — S12c's shape, the same one `project-menu.tsx` uses for a project. NO SUBMIT CONTROL, and that is
          deliberate: `renameSection` is synchronous and local, so there is nothing happening in the background for a
          busy label to say (`busy.test.ts`'s rule, the owner's finding 1 of Story 3.4). The `<form>` stays, because
          a form with a single field and no submit button still submits on Enter — the platform's implicit
          submission — which is how the key reaches Save. */}
      <dialog
        ref={rename}
        onClick={closeOnBackdrop}
        aria-labelledby="layers-rename-title"
        // `renaming` is let go on close, so the next Rename — of the same row too — remounts the field on that row's name
        onClose={() => {
          setNameError(null)
          setRenaming(null)
        }}
        className={`${sheet} gap-[18px]`}
      >
        <h2 id="layers-rename-title" className={title}>
          Rename section
        </h2>
        <form
          onSubmit={(event) => {
            event.preventDefault()
            save()
          }}
          className="flex flex-col gap-[18px]"
        >
          {/* keyed on the row: the field is the DOM's, and a second Rename must open on that row's own name */}
          <TextInput
            key={renaming ? keyOf(renaming) : undefined}
            id={NAME_FIELD}
            name="layerName"
            label="Name"
            defaultValue={renaming?.layerName ?? ''}
            error={nameError}
          />
          <div className="flex justify-end gap-[10px]">
            <Button type="button" variant="secondary" size={36} data-cancel onClick={() => rename.current?.close()}>
              Cancel
            </Button>
            <Button type="button" variant="primary" size={36} onClick={save}>
              Save
            </Button>
          </div>
        </form>
      </dialog>
    </div>
  )
})

/* ─────────────────────────────────────────── Story 5.20 — C3a's "HOW READERS REACH IT" CARD.

   `C Post Body.dc.html:1407-1413`, in the Layers panel of the Paywall canvas, where C3a's left rail draws it at its foot
   (EXPERIENCE.md:218-222 re-specified that rail as Layers plus the switcher's group, so the panel keeps its name and holds
   no rows and no "+ Add section": the paywall is not placed, it is where Ghost cuts a post). The tier line counts the
   source in force's PUBLIC tiers (`tierLine`) and is absent where the site was chosen but its tiers could not be read —
   the pill says why; the link to Ghost admin's Tiers is drawn for a linked site alone, and opens a new tab. */
export function HowReadersReachIt({ tiers, tiersHref }: { tiers: string | null; tiersHref: string | null }) {
  return (
    <section aria-labelledby="paywall-how-heading" data-paywall-how className="m-[10px] mt-auto flex flex-col gap-[7px] rounded border border-line bg-surface p-3">
      <h2 id="paywall-how-heading" className="text-[12px] font-semibold">{PAYWALL_WORDS.howHeading}</h2>
      <p className="text-[11.5px] leading-[1.5] text-ink-soft">{PAYWALL_WORDS.how}</p>
      {tiers === null && tiersHref === null ? null : (
        <div className="flex flex-col gap-1 border-t border-line-faint pt-2">
          {tiers === null ? null : <span data-tier-line className="font-mono text-[10px] text-ink-soft-aa">{tiers}</span>}
          {tiersHref === null ? null : (
            <a href={tiersHref} target="_blank" rel="noreferrer" data-tiers-link className={`self-start rounded-sm text-[11.5px] font-semibold text-coral-text hover:underline ${ring}`}>
              {PAYWALL_WORDS.tiersLink}
              <span className="sr-only"> (opens in a new tab)</span>
            </a>
          )}
        </div>
      )}
    </section>
  )
}
