// NFR-6(c2) — the shim's contract tests, against RECORDED real-Ghost output.
//
// "Shim fidelity is enforced by contract tests asserting each shimmed helper's output matches
// recorded real-Ghost output for a fixed input set" (FR-H5), per-commit and OFFLINE, "with image
// URLs compared, not normalized away, because the canvas shim emits Ghost-shaped sized URLs and
// srcset rather than passing paths through" (NFR-6(c2)).
//
// Three properties this file is built to have, each learned expensively:
//
//   1. **It never skips.** Standing rule 2: a result whose control did not pass is not a result.
//      `recorded()` THROWS a sentence naming the helper and the capture command when a recording is
//      absent, so a missing fixture fails the suite rather than quietly shrinking it. `assertBoth`
//      additionally fails if either major is missing, so a recording captured on one box only
//      cannot look like a pass.
//   2. **It normalises nothing on either side of an image comparison.** That is the one test
//      underwriting the WYSIWYG promise, and normalising is how it passes while being useless.
//   3. **It asserts the INPUT, not just the output.** A recording of Ghost's answer with no record
//      of Ghost's question can only assert that a string equals itself. Every case below feeds the
//      shim the recorded input and compares against the recorded output.
//
// The recordings are imported, not read: AD-1 bans `node:fs` inside a core package and the
// test-file exemption gives back only `node:test` and `node:assert`. `fixtures/index.ts` is
// generated by the capture command over whatever is on disk, so a template added to the probe theme
// cannot go unasserted through a stale import list.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { IMAGE_SIZES, safeCssColor } from '@inflozo/library'
import type { DataBinding } from '@inflozo/library'
import { CAPTURE_COMMAND, RECORDINGS } from '../fixtures/index.ts'
import {
  CONTENT_API_KEY_PLACEHOLDER,
  EXCERPT_DEFAULT_WORDS,
  SAMPLE_MEMBERS,
  TAXONOMY_SEPARATOR,
  assetUrl,
  bareHelper,
  contentApiKey,
  contentApiUrl,
  excerpt,
  formatDate,
  getExprs,
  getQuery,
  ghostColor,
  ghostUrl,
  imgUrl,
  is,
  isMember,
  match,
  navigationItems,
  pageUrl,
  paginationContext,
  readingTime,
  srcset,
  srcsetCandidates,
  t,
  taxonomyItems,
  totalMembers,
} from './index.ts'

// ─── reading a recording, and failing by NAME when there is none ──────────────

const MAJORS = ['5', '6'] as const
type Major = (typeof MAJORS)[number]

type Recording = {
  template: string
  path: string
  uploaded_image: string
  ghost_version: string
  captured: string
  command: string
  site: string
  image_sizes: Record<string, number>
  values: Record<string, Record<string, unknown>>
  raw: Record<string, unknown>
  input: Record<string, unknown>
}

function recording(major: Major, template: string, helper: string): Recording {
  const box = RECORDINGS[`ghost${major}`]
  const rec = box?.[template] as Recording | undefined
  if (rec === undefined) {
    throw new Error(
      `NO RECORDING for "${helper}" — ghost${major}/${template}.json is absent. Capture it: ` +
        `${CAPTURE_COMMAND} ${major}. A contract test with no recording FAILS, naming the helper ` +
        `and the capture command; it never skips and it never passes vacuously (standing rule 2).`,
    )
  }
  return rec
}

/** One recorded value, or a named failure. `group` and `key` are the probe theme's own
 *  `GROUP|key=[…]` coordinates, so a refusal points at the line to add. */
function recorded(major: Major, template: string, group: string, key: string, helper: string): string {
  const rec = recording(major, template, helper)
  const g = rec.values[group]
  if (g === undefined || !Object.prototype.hasOwnProperty.call(g, key)) {
    throw new Error(
      `NO RECORDING for "${helper}" — ghost${major}/${template}.json carries no ${group}|${key}. ` +
        `Add the line to tools/probe/theme-shim/${template.replace(/-page-\d+$/, '')}.hbs and ` +
        `re-run: ${CAPTURE_COMMAND} ${major}.`,
    )
  }
  return String(g[key])
}

function input<T>(major: Major, template: string, key: string, helper: string): T {
  const rec = recording(major, template, helper)
  const v = rec.input[key]
  if (v === undefined) {
    throw new Error(`NO RECORDED INPUT for "${helper}" — ghost${major}/${template}.json has no input.${key}. Re-run: ${CAPTURE_COMMAND}`)
  }
  return v as T
}

/** Runs one assertion per major and requires BOTH to be present. A difference between the majors is
 *  expressed, never averaged: the callback receives the major, so a case that legitimately differs
 *  asserts each side's own recorded string. */
function assertBoth(helper: string, body: (major: Major) => void): void {
  const missing = MAJORS.filter((m) => RECORDINGS[`ghost${m}`] === undefined)
  assert.deepEqual(
    missing,
    [],
    `"${helper}" has no recording for Ghost ${missing.join(' and ')}. Both majors are targets ` +
      `(NFR-7): capture with ${CAPTURE_COMMAND}.`,
  )
  for (const m of MAJORS) body(m)
}

// ─── standing rule 2's own control: the failure path FAILS ────────────────────
//
// "A result whose control did not pass is not a result." The whole suite rests on `recorded()`
// throwing rather than returning undefined when a helper has no recording, so that claim is itself
// asserted — a suite that would silently shrink to nothing if the fixtures went missing is not a
// contract test, and three probes in one session have already returned a convincing "held" that was
// really a broken test.

test('a helper with no recording FAILS, naming the helper and the capture command', () => {
  for (const [fn, what] of [
    [() => recording('6', 'no-such-template', '{{invented}}'), 'a missing template'],
    [() => recorded('6', 'index', 'IMG', 'no_such_key', '{{invented}}'), 'a missing value'],
    [() => input('6', 'index', 'no_such_input', '{{invented}}'), 'a missing input'],
  ] as const) {
    assert.throws(
      fn,
      (e: unknown) => {
        const m = (e as Error).message
        assert.match(m, /\{\{invented\}\}/, `${what}: the failure must name the helper`)
        assert.ok(m.includes(CAPTURE_COMMAND), `${what}: the failure must name the capture command`)
        return true
      },
      `${what} must fail, not skip`,
    )
  }
})

// ─── the recordings are what they claim to be ─────────────────────────────────

test('every recording carries its capture date, its command and the map it was made under', () => {
  assertBoth('the recordings themselves', (major) => {
    const box = RECORDINGS[`ghost${major}`] as Record<string, Recording>
    const names = Object.keys(box)
    assert.ok(names.length > 0, `ghost${major} recorded no templates`)
    for (const name of names) {
      const rec = box[name] as Recording
      assert.match(rec.captured, /^\d{4}-\d\d-\d\d$/, `${name}: no capture date (AD-23)`)
      assert.equal(rec.command, CAPTURE_COMMAND, `${name}: the recording does not name its command`)
      assert.match(rec.ghost_version, new RegExp(`^${major}\\.`), `${name}: wrong major`)
      // NFR-6(c2): the recording is made against an Inflozo-emitted package.json, because Ghost's
      // resize behaviour follows the theme's own map. A recording under any other map is a faithful
      // recording of the wrong theme — which is exactly what tools/stress/build.js's three wrong
      // widths would have produced.
      assert.deepEqual(
        rec.image_sizes,
        IMAGE_SIZES,
        `${name}: recorded under a DIFFERENT image_sizes map than FR-J2's normative one`,
      )
    }
  })
})

test('no recording carries a real Content API key', () => {
  // FR-H5: a key belongs in a deployed theme on the user's own domain and has no business in a
  // screenshot, a snapshot diff or a support session. The recorder keeps its SHAPE instead.
  assertBoth('{{content_api_key}}', (major) => {
    const blob = JSON.stringify(RECORDINGS[`ghost${major}`])
    assert.ok(!/"[0-9a-f]{26}"/.test(blob), 'a 26-hex value is in the fixtures — a key leaked')
    const shape = recording(major, 'index', '{{content_api_key}}').values['CORE']?.['content_api_key_shape'] as
      | { length: number; charclass: string }
      | undefined
    assert.ok(shape !== undefined, 'the key shape was not recorded')
    assert.equal(shape.charclass, 'hex')
    assert.ok(shape.length > 0)
  })
})

// ─── {{img_url}} — compared character for character ───────────────────────────

test('{{img_url}} — a Ghost-hosted image at every image_sizes key, byte for byte', () => {
  assertBoth('{{img_url}}', (major) => {
    const rec = recording(major, 'index', '{{img_url}}')
    // the image the recorder uploaded — recorded, so the test feeds the shim the same INPUT Ghost
    // had. It is an ABSOLUTE same-origin URL, which is the case that matters: Ghost answers with a
    // RELATIVE sized URL, so a canvas that passed the value through would serve the original file.
    const src = rec.uploaded_image
    assert.ok(typeof src === 'string' && src !== '', 'the recording does not say which image it sized')
    assert.ok(src.startsWith(rec.site), 'the recorded image is not same-origin — the case is not exercised')
    const site = rec.site

    for (const key of Object.keys(IMAGE_SIZES)) {
      const want = recorded(major, 'index', 'IMG', `hosted_${key}`, `{{img_url size="${key}"}}`)
      // NOT normalised, on either side. This is the assertion the WYSIWYG promise rests on.
      assert.equal(imgUrl(src, key, { siteUrl: site }), want, `img_url size="${key}" drifted from Ghost`)
    }
    assert.equal(
      imgUrl(src, undefined, { siteUrl: site }),
      recorded(major, 'index', 'IMG', 'hosted_nosize', '{{img_url}} with no size'),
    )
    const first = Object.keys(IMAGE_SIZES)[0] as string
    assert.equal(
      imgUrl(src, first, { siteUrl: site, absolute: true }),
      recorded(major, 'index', 'IMG', 'hosted_absolute', '{{img_url absolute="true"}}'),
    )
    assert.equal(
      imgUrl(src, first, { siteUrl: site, format: 'webp' }),
      recorded(major, 'index', 'IMG', 'hosted_webp', '{{img_url format="webp"}}'),
    )
  })
})

test('{{img_url}} — a relative /content/images/ path is sized the same way', () => {
  const relative = '/content/images/2026/01/relative-probe.jpg'
  assertBoth('{{img_url}} (relative)', (major) => {
    const site = recording(major, 'index', '{{img_url}}').site
    for (const key of Object.keys(IMAGE_SIZES)) {
      assert.equal(
        imgUrl(relative, key, { siteUrl: site }),
        recorded(major, 'index', 'IMG', `relative_${key}`, `{{img_url size="${key}"}}`),
      )
    }
    assert.equal(
      imgUrl(relative, Object.keys(IMAGE_SIZES)[0] as string, { siteUrl: site, absolute: true }),
      recorded(major, 'index', 'IMG', 'relative_absolute', '{{img_url absolute="true"}}'),
    )
  })
})

test('{{img_url}} — an UNLINKED project cannot size: the value passes through unchanged', () => {
  // no siteUrl means no origin to resolve a sized URL against; a relative sized URL would 404 on
  // Inflozo's own origin, so the shim returns what it was given (and srcset repeats it per key)
  const relative = '/content/images/2026/01/relative-probe.jpg'
  for (const key of Object.keys(IMAGE_SIZES)) assert.equal(imgUrl(relative, key), relative)
  assert.ok(srcsetCandidates(relative).every((c) => c.url === relative))
})

test('{{img_url}} — an image Ghost does not host comes back VERBATIM, at every size', () => {
  // The recording, not a guess: Ghost has no rendition for a file it does not serve, so it returns
  // the URL untouched. The shim reproduces that and does not invent a `/size/` segment for it — a
  // seeded feature image is exactly this case, which is why the recorder uploads one of its own.
  const external = 'https://static.ghost.org/v5.0.0/images/publication-cover.jpg'
  assertBoth('{{img_url}} (external)', (major) => {
    const site = recording(major, 'index', '{{img_url}}').site
    for (const key of Object.keys(IMAGE_SIZES)) {
      assert.equal(
        imgUrl(external, key, { siteUrl: site }),
        recorded(major, 'index', 'IMG', `external_${key}`, `{{img_url size="${key}"}} on an external URL`),
      )
    }
    assert.equal(
      imgUrl(external, Object.keys(IMAGE_SIZES)[0] as string, { siteUrl: site, absolute: true }),
      recorded(major, 'index', 'IMG', 'external_absolute', '{{img_url absolute="true"}} on an external URL'),
    )
  })
})

test('a size that is not an image_sizes key is refused, and Ghost shows why it must be', () => {
  assertBoth('{{img_url size="800"}}', (major) => {
    const rec = recording(major, 'index', '{{img_url}}')
    const notakey = recorded(major, 'index', 'IMG', 'hosted_notakey', '{{img_url size="800"}}')
    const nosize = recorded(major, 'index', 'IMG', 'hosted_nosize', '{{img_url}} with no size')
    // THE DEFECT, recorded: `size="800"` returns the ORIGINAL, identical to asking for no size at
    // all, and reports nothing. That is why the grammar narrowed rather than merely tightened.
    assert.equal(notakey, nosize, 'Ghost no longer silently returns the original for a non-key size')
    assert.throws(
      () => imgUrl(rec.site + '/content/images/x.png', '800'),
      (e: unknown) => {
        const m = (e as Error).message
        for (const k of Object.keys(IMAGE_SIZES)) assert.ok(m.includes(k), `the refusal must name "${k}"`)
        return true
      },
    )
  })
})

test('data-bind-srcset composes one candidate per key, from the one map (FR-J5)', () => {
  assertBoth('srcset', (major) => {
    const rec = recording(major, 'index', 'srcset')
    const src = rec.uploaded_image
    const cands = srcsetCandidates(src, { siteUrl: rec.site })
    assert.deepEqual(cands.map((c) => c.width), Object.values(IMAGE_SIZES))
    // every candidate is the RECORDED URL at that key — the candidate list is not a second rule
    for (const c of cands) {
      const key = Object.entries(IMAGE_SIZES).find(([, w]) => w === c.width)?.[0] as string
      assert.equal(c.url, recorded(major, 'index', 'IMG', `hosted_${key}`, `srcset candidate ${key}`))
    }
    assert.equal(srcset(src, { siteUrl: rec.site }), cands.map((c) => `${c.url} ${c.width}w`).join(', '))
  })
})

// ─── {{date}} ─────────────────────────────────────────────────────────────────

test('{{date}} reproduces every recorded format — and the UTC condition is asserted, not assumed', () => {
  assertBoth('{{date}}', (major) => {
    // AD-1 bans Intl and every timezone read, so the shim formats in UTC while Ghost formats in the
    // SITE's timezone. The two agree only while the recording site is UTC. Assert that rather than
    // relying on it: a recording made on a site in another zone must fail HERE, loudly, naming the
    // reason — not silently shift every date on the canvas.
    const tz = recorded(major, 'index', 'SITE', 'timezone', '{{date}}')
    assert.match(
      tz,
      /^(Etc\/)?(UTC|GMT)$/,
      `the recording site's timezone is "${tz}", not UTC. The shim formats in UTC (AD-1 bans Intl and ` +
        `every timezone read), so these recorded strings are no longer comparable. Either record on a ` +
        `UTC site or give the shim a recorded offset as an input.`,
    )
    const post = input<{ published_at: string }>(major, 'post', 'post', '{{date}}')
    const cases: [string, string | undefined][] = [
      ['default', undefined],
      ['d_mmm_yyyy', 'D MMM YYYY'],
      ['yyyy_mm_dd', 'YYYY-MM-DD'],
      ['mmmm_d_yyyy', 'MMMM D, YYYY'],
      ['yy', 'YY'],
      ['dd', 'DD'],
      ['utc_iso', 'YYYY-MM-DDTHH:mm:ssZ'],
      ['utc_d_mmm_yyyy', 'D MMM YYYY'],
    ]
    for (const [key, fmt] of cases) {
      assert.equal(
        formatDate(post.published_at, fmt),
        recorded(major, 'post', 'DATE', key, `{{date format="${fmt ?? '(default)'}"}}`),
        `{{date}} drifted on format ${fmt ?? '(default)'}`,
      )
    }
  })
})

// ─── {{reading_time}}, {{excerpt}}, {{custom_excerpt}}, {{title}}, {{url}} ────

test('{{reading_time}} floors at one minute, the way Ghost does', () => {
  assertBoth('{{reading_time}}', (major) => {
    const post = input<{ reading_time: number }>(major, 'post', 'post', '{{reading_time}}')
    assert.equal(
      readingTime(post.reading_time),
      recorded(major, 'post', 'READ', 'reading_time', '{{reading_time}}'),
    )
    assert.equal(
      readingTime(post.reading_time, { minute: '1 min', minutes: '% mins' }),
      recorded(major, 'post', 'READ', 'reading_time_minute', '{{reading_time minute= minutes=}}'),
    )
    // and the recorded input is the case that matters: the API said 0 and Ghost printed one minute,
    // so a shim that trusted the field would print "0 min read" on every short post.
    assert.ok(readingTime(0).startsWith('1 '), 'a zero reading_time must floor to one minute')
    assert.equal(readingTime(7), '7 min read')
  })
})

test('{{excerpt}} — Ghost own fallback, with words= and characters= as recorded', () => {
  assertBoth('{{excerpt}}', (major) => {
    const post = input<{ excerpt: string; custom_excerpt: string | null }>(major, 'post', 'post', '{{excerpt}}')
    // the recorded post has NO custom excerpt (a third of the seed does, none with markup), so what
    // the recording proves is the computed half;
    // the recorded excerpt is shorter than the 50-word default, which is why the default is
    // observable only as "not truncated" here (read in source: meta/generate-excerpt.js)
    assert.equal(post.custom_excerpt, null, 'the recorded post grew a custom excerpt — re-read this test')
    assert.ok(post.excerpt.split(/\s+/).length < EXCERPT_DEFAULT_WORDS)
    assert.equal(excerpt(post), recorded(major, 'post', 'EXCERPT', 'excerpt', '{{excerpt}}'))
    assert.equal(
      excerpt(post, { words: 10 }),
      recorded(major, 'post', 'EXCERPT', 'excerpt_words_10', '{{excerpt words="10"}}'),
    )
    assert.equal(
      excerpt(post, { characters: 40 }),
      recorded(major, 'post', 'EXCERPT', 'excerpt_characters_40', '{{excerpt characters="40"}}'),
    )
    assert.equal(
      textValueOf(post.custom_excerpt),
      recorded(major, 'post', 'EXCERPT', 'custom_excerpt', '{{custom_excerpt}}'),
    )
  })
  // READ IN SOURCE (helpers/excerpt.js at v5.130.6 and v6.58.0, 2026-09-12): a custom excerpt wins,
  // is never truncated, and markup in it is ESCAPED, never stripped — the first draft stripped tags,
  // which was a visible canvas/site disagreement. A text node of the escaped string is the literal.
  assert.equal(excerpt({ custom_excerpt: '<em>x</em>y', excerpt: 'z' }, { words: 1 }), '<em>x</em>y')
  assert.equal(excerpt({ excerpt: 'a b c' }, { words: 2 }), 'a b')
  const long = Array.from({ length: EXCERPT_DEFAULT_WORDS + 5 }, (_, i) => `w${i}`).join(' ')
  assert.equal(excerpt({ excerpt: long }).split(' ').length, EXCERPT_DEFAULT_WORDS)
})
const textValueOf = (v: unknown): string => (v == null ? '' : String(v))

test('{{title}} and {{url}} come through as the recorded strings', () => {
  assertBoth('{{title}} / {{url}}', (major) => {
    const post = input<{ title: string; url: string }>(major, 'post', 'post', '{{title}}')
    assert.equal(post.title, recorded(major, 'post', 'POST', 'title', '{{title}}'))
    // {{url}} is RELATIVE and {{url absolute="true"}} is not — the API field is the absolute form.
    // The canvas deliberately prints the ABSOLUTE form: a relative href on the canvas would resolve
    // against Inflozo's origin. The relation between the two is what is asserted here.
    const rel = recorded(major, 'post', 'POST', 'url', '{{url}}')
    const abs = recorded(major, 'post', 'POST', 'url_absolute', '{{url absolute="true"}}')
    assert.equal(post.url, abs, 'the API url is not the absolute form the helper prints')
    assert.equal(abs.slice(recording(major, 'post', '{{url}}').site.length), rel)
    assert.equal(ghostUrl(abs), abs, 'a legitimate https URL must survive')
  })
})

// ─── {{tags}} and {{authors}} ─────────────────────────────────────────────────

test('{{tags}} and {{authors}} — the recorded names, separators and autolink form', () => {
  assertBoth('{{tags}} / {{authors}}', (major) => {
    const tags = input<{ name: string; url: string }[]>(major, 'post', 'post_tags', '{{tags}}')
    const authors = input<{ name: string; url: string }[]>(major, 'post', 'post_authors', '{{authors}}')
    const site = recording(major, 'post', '{{tags}}').site
    // the SHIM's items, and Ghost's own markup rebuilt from them — as {{navigation}} is
    const plain = (rows: { name: string; url: string }[], sep = TAXONOMY_SEPARATOR) =>
      taxonomyItems(rows, { siteUrl: site }).map((r) => r.name).join(sep)
    const linked = (rows: { name: string; url: string }[]) =>
      taxonomyItems(rows, { siteUrl: site }).map((r) => `<a href="${r.url}">${r.name}</a>`).join(TAXONOMY_SEPARATOR)
    assert.ok(taxonomyItems(tags, { siteUrl: site }).every((i) => i.url.startsWith('/')), 'the href is relative, as recorded')

    assert.equal(plain(tags), recorded(major, 'post', 'TAGS', 'tags_plain', '{{tags autolink="false"}}'))
    assert.equal(plain(tags, ' / '), recorded(major, 'post', 'TAGS', 'tags_sep', '{{tags separator=" / "}}'))
    assert.equal(linked(tags), recorded(major, 'post', 'TAGS', 'tags', '{{tags}}'))
    assert.equal(plain(authors), recorded(major, 'post', 'AUTHORS', 'authors_plain', '{{authors autolink="false"}}'))
    assert.equal(linked(authors), recorded(major, 'post', 'AUTHORS', 'authors', '{{authors}}'))
  })
})

// ─── the four core helpers ────────────────────────────────────────────────────

test('{{total_members}} — the recorded count produces the recorded string, on each major', () => {
  assertBoth('{{total_members}}', (major) => {
    const members = input<{ total: number; paid: number }>(major, 'index', 'members', '{{total_members}}')
    const want = recorded(major, 'index', 'CORE', 'total_members', '{{total_members}}')
    assert.equal(totalMembers(members.total, major), want, `{{total_members}} drifted on Ghost ${major}`)
    assert.equal(
      totalMembers(members.paid, major),
      recorded(major, 'index', 'CORE', 'total_paid_members', '{{total_paid_members}}'),
    )
    // FR-H5: always a string, never a number
    assert.equal(typeof totalMembers(members.total, major), 'string')
  })
  // The two majors are expressed, never averaged: each side is asserted against ITS OWN recording
  // above, and nothing here asserts the two boxes hold the same count. The divergence MEASUREMENTS
  // §15f executed (Ghost 6 comma-formats at ≤ 50 and counts gift subscriptions, Ghost 5 does
  // neither) produces identical strings for every count under 1,000, so it is not observable below.
  assert.equal(totalMembers(1234, '6'), totalMembers(1234, '5'))
  assert.equal(totalMembers(45, '6'), '45')
  assert.equal(totalMembers(45, '5'), '45')
  assert.equal(totalMembers(1234, '6'), '1,200+')
  // MEASUREMENTS §15f's bracket table, which is the half no single count can show
  assert.equal(totalMembers(50, '6'), '50', '≤ 50 is EXACT and carries no + — the PRD says otherwise and is wrong')
  assert.equal(totalMembers(57, '6'), '50+')
  assert.equal(totalMembers(101, '6'), '100+')
  assert.equal(totalMembers(1001, '6'), '1,000+')
  assert.equal(totalMembers(10001, '6'), '10,000+')
  // above 100,000 MEASUREMENTS records only "humanNumber lowercased" and no execution
  assert.throws(() => totalMembers(200000, '6'), /not recorded/)
  // FR-H5: a SAMPLE value on an unlinked project, in the rounded shape a real site over 50 has
  assert.equal(bareHelper('total_members'), totalMembers(SAMPLE_MEMBERS.total, '6'))
  assert.match(bareHelper('total_members'), /\+$/)
  assert.equal(bareHelper('total_paid_members'), totalMembers(SAMPLE_MEMBERS.paid, '6'))
  // LINKED is "a site", and a linked site with no count refuses rather than posing as the sample
  assert.throws(() => bareHelper('total_members', { siteUrl: 'https://s.example' }), /needs members.total/)
  assert.equal(bareHelper('total_members', { siteUrl: 'https://s.example', members: { total: 57 }, major: '5' }), '50+')
})

test('{{content_api_key}} renders an inert placeholder and the key is absent from the output', () => {
  assert.equal(contentApiKey(), CONTENT_API_KEY_PLACEHOLDER)
  assert.ok(!/^[0-9a-f]{26}$/.test(contentApiKey()), 'the placeholder must not look like a key')
  assert.equal(bareHelper('content_api_key'), CONTENT_API_KEY_PLACEHOLDER)
  assertBoth('{{content_api_key}}', (major) => {
    const shape = recording(major, 'index', '{{content_api_key}}').values['CORE']?.['content_api_key_shape'] as
      { length: number }
    assert.notEqual(contentApiKey().length, shape.length, 'the placeholder must not even be key-shaped')
  })
})

test('{{content_api_url}} is the recorded string', () => {
  assertBoth('{{content_api_url}}', (major) => {
    const site = recording(major, 'index', '{{content_api_url}}').site
    assert.equal(
      contentApiUrl(site),
      recorded(major, 'index', 'CORE', 'content_api_url', '{{content_api_url}}'),
    )
  })
})

// ─── {{asset}}, {{navigation}}, pagination ────────────────────────────────────

test('{{asset}} versions the path the way the recording shows', () => {
  assertBoth('{{asset}}', (major) => {
    const want = recorded(major, 'index', 'ASSET', 'screen_css', '{{asset}}')
    const version = want.split('?v=')[1] as string
    assert.equal(assetUrl('css/screen.css', version), want)
    assert.equal(assetUrl('/css/screen.css', version), want, 'a leading slash must not double up')
  })
})

test('{{navigation}} rebuilds Ghost own markup from the recorded items', () => {
  assertBoth('{{navigation}}', (major) => {
    const rec = recording(major, 'index', '{{navigation}}')
    const nav = String(rec.raw['navigation'] ?? '')
    const lines = String(rec.raw['nav-items'] ?? '')
      .split('\n')
      .map((l) => /^NAV\|label=\[(.*?)\]\|url=\[(.*?)\]\|current=\[(.*?)\]$/.exec(l.trim()))
      .filter((m): m is RegExpExecArray => m !== null)
      .map((m) => ({ label: m[1] as string, url: m[2] as string, current: m[3] === 'true' }))
    assert.ok(lines.length > 0, 'the recording carries no navigation items')
    // Ghost marks the item whose url IS the page being rendered, which is why the shim takes the
    // current URL rather than trusting the item's own `current` field — `@site.navigation` carries
    // it empty (recorded), and Ghost's own partial computes it.
    // the shim absolutises a site-relative item as Ghost's partial does — the href is compared byte
    // for byte below, not re-absolutised by this test
    const items = navigationItems(lines, { currentUrl: rec.path, siteUrl: rec.site })
    // Ghost's own navigation partial, reproduced from the shim's items. The shim returns DATA and
    // never a node, because NFR-3 puts every Ghost value in a text node and a function with no DOM
    // cannot break that rule by accident.
    const site = rec.site
    const built = `<ul class="nav">\n${items
      .map((i) => `    <li class="${i.className}"><a href="${i.url}">${i.label}</a></li>`)
      .join('\n')}\n</ul>\n`
    assert.equal(built, nav, 'the navigation markup drifted from Ghost')
  })
})

test('the pagination context and {{page_url}} match the recorded middle page', () => {
  assertBoth('pagination', (major) => {
    const g = recording(major, 'index-page-2', 'pagination').values['PAGE'] as Record<string, string>
    const ctx = paginationContext({ page: g['page'] ?? g['pagination_page'], pages: g['pagination_pages'], limit: g['pagination_limit'], total: g['pagination_total'] })
    assert.equal(String(ctx.page), g['pagination_page'])
    assert.equal(String(ctx.pages), g['pagination_pages'])
    assert.equal(String(ctx.limit), g['pagination_limit'])
    assert.equal(String(ctx.total), g['pagination_total'])
    assert.equal(String(ctx.next), g['pagination_next'], 'the derived next page differs from Ghost')
    assert.equal(String(ctx.prev), g['pagination_prev'], 'the derived prev page differs from Ghost')
    assert.equal(pageUrl(ctx.next), g['page_url_next'])
    assert.equal(pageUrl(ctx.prev), g['page_url_prev'])
    // page 1 of the same feed: a true middle page and a first page are both recorded, which is what
    // makes "both links present" and "one link absent" two assertions rather than one.
    const one = recording(major, 'index', 'pagination').values['PAGE'] as Record<string, string>
    const first = paginationContext({ page: one['pagination_page'], pages: one['pagination_pages'] })
    assert.equal(first.prev, null)
    assert.equal(String(first.next), one['pagination_next'])
  })
})

// ─── the truthy helpers, {{#match}}, {{#if @member}} ──────────────────────────

test('{{#match}}, {{#is}} and {{#if @member}} agree with the recorded arms', () => {
  assertBoth('{{#match}} / {{#is}} / {{#if @member}}', (major) => {
    const site = recording(major, 'index', '{{#match}}').values
    const locale = String((site['SITE'] as Record<string, string>)['locale'])
    const ppp = String((site['SITE'] as Record<string, string>)['posts_per_page'])
    const yn = (b: boolean) => (b ? 'YES' : 'NO')
    assert.equal(yn(match(locale, locale)), recorded(major, 'index', 'MATCH', 'locale_true', '{{#match}}'))
    assert.equal(yn(match(locale, 'zz-ZZ')), recorded(major, 'index', 'MATCH', 'locale_false', '{{#match}}'))
    assert.equal(yn(match(ppp, '>', 1)), recorded(major, 'index', 'MATCH', 'op_gt', '{{#match a ">" b}}'))
    assert.equal(yn(is('index', 'index')), recorded(major, 'index', 'TRUTHY', 'is_index', '{{#is}}'))
    assert.equal(yn(is('index', 'post')), recorded(major, 'index', 'TRUTHY', 'is_post', '{{#is}}'))
    assert.equal(yn(is('post', 'post')), recorded(major, 'post', 'TRUTHY', 'is_post', '{{#is}}'))
    // the post's own visibility, through {{#match}} — a tier badge tests equality, never !== public
    const vis = recorded(major, 'post', 'POST', 'visibility', '{{#match visibility "public"}}')
    assert.equal(yn(match(vis, 'public')), recorded(major, 'post', 'MATCH', 'visibility_public', '{{#match}}'))
    // the canvas renders as ANONYMOUS unless told otherwise, which is what the recording shows
    const member = recorded(major, 'index', 'MEMBER', 'if_member', '{{#if @member}}')
    assert.equal(isMember(undefined) ? 'SIGNED_IN' : 'ANONYMOUS', member)
    assert.equal(isMember({ uuid: 'x' }), true)
  })
  assert.throws(() => match(1, 'like', 2), /is not one of/)
})

// ─── {{#get}} ─────────────────────────────────────────────────────────────────

test('{{#get}} builds the Content API query from the DECLARATION, and the recording proves it ran', () => {
  const bindings: Record<string, DataBinding> = {
    featured_craft: { source: 'posts', filter: 'tag:craft+featured:true', limit: 3, order: 'published_at desc' },
    picked: { source: 'posts', ids: ['aaa', 'bbb'] },
  }
  assertBoth('{{#get}}', (major) => {
    const filter = recorded(major, 'index', 'GET', 'filter', '{{#get}}')
    const rows = recorded(major, 'index', 'GET', 'craft_featured', '{{#get}}')
    const declared = bindings['featured_craft'] as DataBinding
    assert.equal(declared.filter, filter, 'the declaration and the recorded filter differ')
    assert.ok(rows !== 'BLOCK_DID_NOT_RUN', 'the recorded {{#get}} returned nothing — the fixture proves nothing')
    const slugs = rows.split(',').filter((s) => s !== '')
    assert.ok(
      slugs.length <= (declared.limit as number),
      `Ghost returned ${slugs.length} rows for limit="${declared.limit}"`,
    )
    const [q] = getQuery('featured_craft', bindings)
    assert.deepEqual(q, {
      resource: 'posts',
      params: { filter: filter, limit: '3', order: 'published_at desc' },
    })
    assert.deepEqual(
      getExprs('featured_craft', bindings),
      [`{{#get "posts" filter="${filter}" limit="3" order="published_at desc"}}`],
    )
  })
  // R-20: a hand-picked order is N single-id gets, IN THAT ORDER — on BOTH halves
  assert.deepEqual(getQuery('picked', bindings).map((q) => q.params['filter']), ['id:aaa', 'id:bbb'])
  assert.deepEqual(getExprs('picked', bindings), [
    '{{#get "posts" filter="id:aaa" limit="1"}}',
    '{{#get "posts" filter="id:bbb" limit="1"}}',
  ])
  // the LIBRARY's declaration grammar runs at emission too — one copy, called twice
  assert.throws(() => getExprs('none', { none: { source: 'posts', ids: [] } }), /bad-get-ids/)
  assert.throws(() => getExprs('sp', { sp: { source: 'posts', ids: ['a b'] } }), /bad-get-ids/)
  assert.throws(() => getExprs('both', { both: { source: 'posts', ids: ['a'], limit: 2 } }), /bad-get-ids/)
  assert.throws(() => getExprs('big', { big: { source: 'posts', limit: 500 } }), /bad-get-limit/)
  assert.throws(() => getExprs('camelKey', { camelKey: { source: 'posts' } }), /bad-get-key/)
  assert.throws(() => getExprs('o', { o: { source: 'posts', order: '@x' } }), /TEMPLATE-level context only/)
  assert.throws(() => getExprs('bs', { bs: { source: 'posts', filter: 'tag:x\\' } }), /quote, a backslash or a line break/)
  // AD-36 (2) at EMISSION: a value that would close the expression is refused, validator or not
  assert.throws(() => getExprs('q', { q: { source: 'posts', filter: 'tag:x" }}<script>' } }), /quote, a backslash or a line break/)
  assert.throws(() => getExprs('q', { q: { source: 'posts', order: 'slug asc\n' } }), /quote, a backslash or a line break/)
  // a literal that merely CONTAINS "this" is a legitimate NQL value
  assert.equal(getExprs('w', { w: { source: 'posts', filter: 'tag:this-week' } })[0], '{{#get "posts" filter="tag:this-week"}}')
  // an undeclared key, and a filter reaching for the current row
  assert.throws(() => getQuery('nope', bindings), /names no dataBindings key/)
  assert.throws(
    () => getQuery('ctx', { ctx: { source: 'posts', filter: 'tag:this.slug' } }),
    /TEMPLATE-level context only/,
  )
  assert.throws(
    () => getQuery('ctx', { ctx: { source: 'posts', filter: 'tag:{{slug}}' } }),
    /TEMPLATE-level context only/,
  )
  assert.throws(() => getQuery('bad', { bad: { source: 'settings' } }), /not queryable/)
})

// ─── NFR-3's three carve-outs, and AD-36's paired assertions ──────────────────

test('AD-36 — a hostile Ghost URL is inert and the legitimate one beside it still works', () => {
  for (const hostile of [
    'javascript:alert(1)',
    'JaVaScRiPt:alert(1)',
    'java\nscript:alert(1)',
    'data:text/html,<script>alert(1)</script>',
    'vbscript:msgbox(1)',
    // narrower than safeUrl's USER allow-list, deliberately: a mailto: in @site.logo is not a
    // feature, it is a compromised or confused field (SPINE Conventions row)
    'mailto:someone@example.com',
    'tel:+15551234',
  ]) {
    assert.equal(ghostUrl(hostile), '#', `${hostile} was not neutralised`)
  }
  assertBoth('Ghost URL fields', (major) => {
    // the legitimate half, from the recording rather than from an example
    const site = recording(major, 'index', 'Ghost URL fields').site
    assert.equal(ghostUrl(site), site)
    const cover = recorded(major, 'index', 'SITE', 'cover_image', '@site.cover_image')
    if (cover !== '') assert.equal(ghostUrl(cover), cover, 'a real Ghost image URL was mangled')
    const url = recorded(major, 'post', 'POST', 'url', '{{url}}')
    assert.equal(ghostUrl(url), url, 'a relative Ghost URL must survive')
  })
})

test('AD-36 / DW-95 — a Ghost colour that is not a colour falls back, and a real one survives', () => {
  // Ghost stores accent_color VERBATIM: all four of these were ACCEPTED on both live majors
  // (MEASUREMENTS §21e, executed), so the value crossing into a CSS declaration is not necessarily
  // a colour. The shim calls the LIBRARY's parser — one copy, which is the whole of DW-95.
  for (const hostile of [
    'red;}body{display:none',
    '#fff;background:url(x)',
    '#fff;width:100vw',
    '#f00;/* c */color:red',
    'red',
  ]) {
    assert.equal(ghostColor(hostile), 'var(--accent)', `${hostile} was not neutralised`)
  }
  assert.equal(ghostColor('#f0f'), '#f0f', 'the legitimate value beside it must still work')
  assert.equal(ghostColor('rgb(255, 0, 255)'), 'rgb(255, 0, 255)')
  assertBoth('a Ghost colour', (major) => {
    const accent = recorded(major, 'index', 'SITE', 'accent_color', '@site.accent_color')
    assert.equal(ghostColor(accent), accent, `the site's real accent colour ${accent} was refused`)
    // and it is the library's one copy, not a second parser grown here
    assert.equal(ghostColor(accent), safeCssColor(accent, '--accent'))
  })
})

// ─── {{t}} ────────────────────────────────────────────────────────────────────

test('{{t}} prints the key when the catalog has no entry, as Ghost does, and fills {placeholders}', () => {
  assertBoth('{{t}}', (major) => {
    // the probe theme ships no locales/, so this is the recorded no-entry case
    assert.equal(t('Older posts'), recorded(major, 'index', 'TEXT', 't_unknown', '{{t "Older posts"}}'))
  })
  assert.equal(t('pager.older', { n: 3 }, { 'pager.older': '{n} older posts' }), '3 older posts')
  assert.equal(t('pager.older', {}, { 'pager.older': '{n} older posts' }), '{n} older posts', 'an unfilled placeholder stays VISIBLE')
  assert.equal(t('constructor'), 'constructor', 'a prototype name is a key like any other')
})

// ─── the bare helpers ─────────────────────────────────────────────────────────

test('data-helper="content" with no fixture REFUSES rather than inventing a body', () => {
  assert.throws(() => bareHelper('content'), /FR-H3/)
  assert.throws(() => bareHelper('comments'), /FR-H3/)
  assert.equal(bareHelper('content', { fixtures: { content: '<p>the style-guide post</p>' } }), '<p>the style-guide post</p>')
})

test('data-helper="statusCode" and "message" read the recorded error page', () => {
  assertBoth('{{statusCode}} / {{message}}', (major) => {
    const code = recorded(major, 'error', 'ERROR', 'status_code', '{{statusCode}}')
    const message = recorded(major, 'error', 'ERROR', 'message', '{{message}}')
    const ghost = { statusCode: Number(code), message }
    assert.equal(bareHelper('statusCode', { ghost }), code)
    assert.equal(bareHelper('message', { ghost }), message)
  })
})

test('data-helper="total_members" reads the recorded count through the bracket function', () => {
  assertBoth('{{total_members}} via data-helper', (major) => {
    const members = input<{ total: number }>(major, 'index', 'members', '{{total_members}}')
    assert.equal(
      bareHelper('total_members', { members, major, siteUrl: recording(major, 'index', '{{total_members}}').site }),
      recorded(major, 'index', 'CORE', 'total_members', '{{total_members}}'),
    )
  })
})
