/* D5a · THE AUTO-GENERATED MARKER (`D5 Canvas Markers and Template Switcher.dc.html`:28-97) — the same sentence in
   two places, and both vanish on the first edit.

   ONE SENTENCE, WRITTEN ONCE. "Auto-generated — edit anything to make it yours" is APP COPY and never a theme string
   (`prd.md:1337`), and FR-D6 names both places it appears: beside the Template control in the top bar, and at the head
   of the Layers panel. It carries NO keyboard shortcut, deliberately (FR-D11) — it is a statement, not a control.

   THE TWO SHAPES, MEASURED OFF THE FRAME. The chip (:39) is 32px tall, 11px padding, 7px gap, white on a 1px `line`
   border at radius 8, with a 9px hollow dot (1.5px `line-strong`) and 12px `ink-soft` words. The Layers row (:54-57)
   is `paper-raised` on a 1px `line` border at radius 10, 9/10 padding, an 8px gap, the dot pushed 4px down to sit on
   the first line of 11.5px `ink-soft-aa` words that wrap.

   WHERE IT SITS, AGAINST R-126. R-126 drew the Layers panel for its NAMES: two groups the same shape with a hairline,
   no card, no glyph, no footed note. This is a different element with a different job — it is about the CANVAS, not a
   group — so it sits ABOVE both groups and takes nothing from either heading, and R-126 stands untouched. */

const WORDS = 'Auto-generated — edit anything to make it yours'

/** D5a's hollow ring — the same 9px dot in both places. */
const Ring = ({ className }: { className?: string }) => (
  <span aria-hidden className={`size-[9px] shrink-0 rounded-full border-[1.5px] border-line-strong ${className ?? ''}`} />
)

/** The top bar's chip, beside the Template control. */
export const AutoGeneratedChip = () => (
  <span data-auto-generated="bar" className="flex h-8 items-center gap-[7px] rounded-sm border border-line bg-surface px-[11px]">
    <Ring />
    <span className="text-control-label text-ink-soft">{WORDS}</span>
  </span>
)

/** The row at the head of Layers, above both groups. */
export const AutoGeneratedRow = () => (
  <div data-auto-generated="layers" className="flex items-start gap-2 rounded-thumb border border-line bg-paper-raised p-[9px_10px]">
    <Ring className="mt-1" />
    <span className="text-[11.5px] leading-[1.5] text-ink-soft-aa text-pretty">{WORDS}</span>
  </div>
)
