/* D5a · THE AUTO-GENERATED MARKER (`D5 Canvas Markers and Template Switcher.dc.html`:28-97) — at the head of the
   Layers panel, and gone on the first edit.

   ONE PLACE, NOT TWO (ruling R-130, the owner, 2026-09-18). FR-D6 and D5a name two: a chip beside the Template
   control in the top bar, and this row. The owner removed the chip at his test of Story 5.5 — "We already have the
   identifier in the Dropdown" — and he is right that it was the third time the same fact was stated on one screen:
   the switcher's closed control names the canvas, its row carries a hollow dot AND the word "Auto-generated", and the
   chip then repeated the whole sentence beside it. The Layers row stays because it is the only one of the three that
   a user reading the SECTION LIST sees without opening anything. D5a is superseded on the chip alone; its Layers row
   is unchanged, measure for measure, and R-74 stands everywhere else.

   ONE SENTENCE, WRITTEN ONCE. "Auto-generated — edit anything to make it yours" is APP COPY and never a theme string
   (`prd.md:1337`). It carries NO keyboard shortcut, deliberately (FR-D11) — it is a statement, not a control.

   THE SHAPE, MEASURED OFF THE FRAME. The row (:54-57) is `paper-raised` on a 1px `line` border at radius 10, 9/10
   padding, an 8px gap, a 9px hollow dot (1.5px `line-strong`) pushed 4px down to sit on the first line of 11.5px
   `ink-soft-aa` words that wrap.

   WHERE IT SITS, AGAINST R-126. R-126 drew the Layers panel for its NAMES: two groups the same shape with a hairline,
   no card, no glyph, no footed note. This is a different element with a different job — it is about the CANVAS, not a
   group — so it sits ABOVE both groups and takes nothing from either heading, and R-126 stands untouched. */

const WORDS = 'Auto-generated — edit anything to make it yours'

/** The row at the head of Layers, above both groups — the marker's one place (R-130). */
export const AutoGeneratedRow = () => (
  <div data-auto-generated="layers" className="flex items-start gap-2 rounded-thumb border border-line bg-paper-raised p-[9px_10px]">
    <span aria-hidden className="mt-1 size-[9px] shrink-0 rounded-full border-[1.5px] border-line-strong" />
    <span className="text-[11.5px] leading-[1.5] text-ink-soft-aa text-pretty">{WORDS}</span>
  </div>
)
